fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    openvpn: "https://github.com/opus-codium/puppet-openvpn"
  symlinks:
    puppetvpn: "#{source_dir}"
